set -g default-terminal "screen-256color"
set -g status-bg "#779EF1"
set -g base-index 1
set -g renumber-windows on
set-option -g status-right ""
set -g mouse on

bind '"' split-window -c "#{pane_current_path}"
bind % split-window -h -c "#{pane_current_path}"
bind c new-window -c "#{pane_current_path}"

set -gq allow-passthrough on
set -g visual-activity off

bind-key -r f run-shell "tmux neww tmux-sessionizer"

